<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDYvBcTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDYvBcTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDYvBcTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDYvBcTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDYvBcTx\App_KernelDevDebugContainer([
    'container.build_hash' => 'DYvBcTx',
    'container.build_id' => 'e8ef8cf8',
    'container.build_time' => 1657997316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDYvBcTx');
