<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKm5fvj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKm5fvj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKm5fvj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKm5fvj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNKm5fvj\App_KernelDevDebugContainer([
    'container.build_hash' => 'NKm5fvj',
    'container.build_id' => '9463a39d',
    'container.build_time' => 1658065056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKm5fvj');
